name: "Validate Gradle Wrapper"

on:
    push:
        branches: [ stable-3.13 ]
    pull_request:
        branches: [ stable-3.13 ]

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: gradle/wrapper-validation-action@v1
